### PR TITLE
Improve README syntax, grammar and content

### PR DESCRIPTION
**Pull request by Undistraction**
- Fix grammatical errors
- Fix syntax errors
- Minor edits of content for clarity

### CODE REVIEW

**Comment by aFarkas** [comment]
First of all many thanks! I have found two things, I would like to change:

I would remove/change the following:

> Lazysizes recognises a set of data attributes that work similarly to then new responsive image html spec, but adds powerful additional functionality...

Lazysizes does not do something similar to the respimg spec. Lazysizes is built upon this spec and extends it with some powerful functionality. In case the browser supports `srcset` it simply transforms the `data-*` attribute to `srcset` and in case the browser doesn't support it a polyfill can be used. The fact that the simple respimg polyfill plugin does only work with `data-*` and not directly with `srcset` is simply just caused by the fact that the plugin doesn't search the DOM for responsive images on its own, it simply waits for lazysizes event `lazybeforesizes` event to do its job.

This is basically analog to a normal lazyloader, which transforms `data-src` or `data-original` attributes into `src` attributes. In that case you wouldn't write either: 

This layzloader recognises a data attribute that work similar to the image `src` spec.

It is also important, to be clear, that this is 100% standard compatible. There are other "lazyloader"/"image handling" scripts, which do have a `data-srcset` attribute, which looks like the specified one, but the inner workings are similar but (totally) different.

----------

I would remove/change the following:

> ... and give the image a percentage width.

This is basically not true. If you use different px units on different viewport widths it still makes sense.

I.e:

```
sizes="(min-width: 800px) 800px, 400px"
```

vs.

```
data-sizes="auto"
```

`data-sizes="auto"` is always helpfull, if you normally would need to write a `sizes`.

**Comment by Undistraction** [comment]
I will amend this tomorrow morning with a clear head.

**Comment by Undistraction** [comment]
Hi Alexander. I think I've folded your notes in appropriately. I have to say I still think the section on responsive images (that I've moved below the intro) is confusing. I don't think its entirely clear in what situation it is appropriate to use 1) Just lazysizes, 2) lazysizes with the respimage plugin 3) Picturefill / respimage without lazysizes at all. I think it would greatly improve the docs if you could add a brief explaination for those three cases. It might actually make sense to flip it the other way and write it as a list of things people might want and which of the three solutions above is best for each of them. Anyway, happy to help if I can.

**Comment by aFarkas** [comment]
>  I don't think its entirely clear in what situation it is appropriate to use ...
> 1) Just lazysizes

..., if you don't have responsive images or if you don't want to polyfill responsive images and simply combine the `data-srcset` for supporting browsers with an additional `data-src` for not-supporting browsers.

> 2) lazysizes with the respimage plugin

If all your responsive images are lazyloaded or autosized by lazySizes.

> 3) Picturefill / respimage without lazysizes at all

If you don't need lazyloading or autosizing.

> 4) lazysizes in combination with picturefill/respimage

If some responsive image should be autosized or lazyloaded by lazysizes and some others shouldn't be lazyloaded.

**Comment by Undistraction** [comment]
Shall I add that to the README?

**Comment by aFarkas** [comment]
I think 1) and 3) aren't that important. But understanding a) the difference between 2) respimg plugin vs 4) full polyfill is important. 

And from 1) it's also important to know, that you can optionally also use `data-src` instead of any kind of a polyfill as a fallback.

**Comment by Undistraction** [comment]
I think seeing all four side-by-side is really helpful in understanding how lazysizes fits in. Coming to this cold I found it difficult to understand how it related to respimage / Picturefill. I've reordered the points as I think this makes more sense. I think point 2. Is still unclear though.

**Comment by aFarkas** [comment]
It seems there are now some mistakes sneaked in:

> Just lazysites

Just lazysizes

> If you want to lazyloaded or lazysize some of your responsive images and not others.

If you want to lazyload or lazysize some of your responsive images and not others.

Point 2 has to decided against Point 3. If all responsive images are lazyloaded or autosized use respimage plugin. If at least one of your responsive images (for example the page logo) is neither autosized nor lazyloaded use a full polyfill.

Is this now clearer?

**Comment by Undistraction** [comment]
Thinking about it some more, I think what isn't explicitly clear from the docs are the points where lazyimages use of `data-*` attributes overlap with the responsive image spec's non `data` prefixed attributes - How does lazyimages / the respimage plugin handle existing 'srcset` / `sizes` attributes? Does it ever add them? Will it use them instead of the `data-` prefixes if they are present? These are important points that I don't think are covered in the docs.

**Comment by aFarkas** [comment]
Actually this should be clear. lazysizes always transforms `data-srcset` to `srcset`. The respimg plugin picks the `srcset` attribute, but it only handles images which are unveiled by lazysizes and it only handles simple sizes or autosized images. This is explained in https://github.com/aFarkas/lazysizes/blob/gh-pages/plugins/respimg/ls.respimg.js.

I think all nuances shouldn't be described in the main documentation. This should be still documented on the corresponding plugin site.

**Pull request merged**
