### PR TITLE
Add module name in AMD define() (fixes #220)

### LINKED ISSUE #220: Conflicts with Require.js when loaded outside require() method
I have a situation with a Require.js powered page, where in order to speed up lazysizes load time, I have moved it out of main.js into html itself:

```html
<script>
 	// require config goes here
	var require = {{ require_config }};
</script>
<script src="{{ require_src }}" data-main="{{ require_main }}" async defer></script>
<script src="{{ lazysizes_src }}" async defer></script>
```

This set up produces the following error:

```
Uncaught Error: Mismatched anonymous define() module: [object Object]
http://requirejs.org/docs/errors.html#mismatch
```

Which leads to the point, that currently lazysizes does not announce its own name when it registers with AMD define():

```javascript
	if (typeof define == 'function' && define.amd) {
		define(lazySizes);
	}
```

I'd like to propose using following code instead:

```javascript
	if (typeof define == 'function' && define.amd) {
		define('lazysizes', [], lazySizes);
	}
```

A PR will follow.

### PR DESCRIPTION
**Pull request by shimonenator**

### CODE REVIEW

**Comment by aFarkas** [comment]
I don't think I can do this. 

What do you think, if I provide a module-less file?

**Comment by shimonenator** [comment]
That's fine with me too, but before you do that, why can't you name the module? The reason I've offered such a solution is because that's how jQuery does it.

**Comment by aFarkas** [comment]
I know, but this changes thing with some bundlers. This why often jquery has to be configured with require.js.

This is directly from jQuery's source code:

```
// Note that for maximum portability, libraries that are not jQuery should
// declare themselves as anonymous modules, and avoid setting a global if an
// AMD loader is present. jQuery is a special case. For more information, see
// https://github.com/jrburke/requirejs/wiki/Updating-existing-libraries#wiki-anon
```

**Comment by shimonenator** [comment]
Can't disagree with that. Perhaps we should not make any change at all then. Thank you for clarifying.

**Comment by aFarkas** [comment]
@AQwebDev 
This fix won'T make it in master. What I can do is to produce a module-less version. Is this what you want?

**Comment by klopfdreh** [comment]
Hi,

I also can't agree with the jQuery documentation, because there will be always issues if you use define anonymously within a separate js file which is going to be loaded via requirejs:

http://requirejs.org/docs/errors.html#mismatch

> If you manually code a script tag in HTML to load a script with an anonymous define() call, this error can occur.

@aFarkas I think the issue you mentioned is that if lazysizes is loaded as AMD the window load event has already been fired - right?

So maybe there is a workaround to fix this:
```javascript
        var loadEventFired = setInterval(function() {
            if (typeof window.domLoadEventFired !== undefined) {
                clearInterval(loadEventFired);
                // your code goes here
            }
        }, motionbreakpoints.loadCheckInterval);
```

I think the best way would be that if lazysizes is loaded as AMD you should use define with a name "lazysizes" and directly require it at the bottom require("lazysizes");

In addition I would use the interval instead of the load event you bind on window if it is not an AMD.

requirejs and other frameworks are also using "hacks" to get a rid of the domReady event, because if the scripts are loaded they can not assure the event has not already been executed.

http://requirejs.org/docs/api.html#pageload
https://github.com/requirejs/domReady/blob/master/domReady.js

WDYT?

**Comment by aFarkas** [comment]
@klopfdreh 

> I also can't agree with the jQuery documentation, because there will be always issues if you use define anonymously within a separate js file which is going to be loaded via requirejs

Yes, but loading modules outside of a bundle isn't the normal way. The problem is, that lazysizes should have been used this, but it's too late for this.

> @aFarkas I think the issue you mentioned is that if lazysizes is loaded as AMD the window load event has already been fired - right?

No this isn't a problem of lazsizes. Lazysizes doesn't need this. And beside this detecting page onload works pretty simple cross browser:

```js
document.readyState == 'complete';
```

Detecting DOM ready was a pain in the ass in the past, but with modern browsers you can simple do this:

```js
/c|d/.test(document.readyState);
```

The main problem is, that this is now a big API change. A lot of people are using lazysizes the following way:

```js
define(['jquery', 'bower_components/foo/foo', 'bower_components/lazysizes/lazsysizes'], function()[

});
```

Changing to a named module breaks things for them.

The simplest way is to simply provide a different file, which has no module definition. I think this is really the cleanest solution, if you don't use lazysizes inside of your AMD bundle don't use the AMD file at all.

Beside of all this. webpack and browserify don't have these problems. It is pretty simple how you reference your own modules and third party modules. It is even so simple to create multiple entry points (one small one with lazysizes) and another with most of your other modules.

I will produce a new lazysizes version on friday, which will have the new files in it.

**Pull request closed without merging**
