### PR TITLE
Update ls.blur-up.js - Add webP to image types

### PR DESCRIPTION
**Pull request by rjsworking**
This small change allows one to have different types low resolution images.

```
<picture>
    <source 
        data-srcset=" ... webp images ..."
        data-lowsrc="low_res.webp"  <---
        type="image/webp"/>

    <source 
        data-srcset=" ... jpeg images ..."
        data-lowsrc="low_res.jpg"  <---
        type="image/jpeg"/>

    <img class="lazyload" data-sizes="auto" />
</picture>

```

### CODE REVIEW

**Comment by aFarkas** [comment]
Sadly this won't cut it. Because this would mean that webp not supporting browser would also load webp.

**Comment by rjsworking** [comment]
True. My fault. Tested with an old browser now. Sorry for the inconvenience.
Is there a way to acomplish this
'

**Comment by aFarkas** [comment]
Yes, I see two possibilities:

1. instead of building a blur up `img` structure, build a blur up ´picture`.
2. make the supported types regexp public and let it to the dev to do some feature detection or browser sniffing so he can extend it.

**Comment by rjsworking** [comment]
Thanky you very much for the suggestions. Option 1) seems fine.
Will close this thread and delete the branch.

**Pull request closed without merging**
