### PR TITLE
checks if window is defined (Adds compatibility with Angular SSR)

### PR DESCRIPTION
**Pull request by JohannesHoppe**
I tried to execute the script with the Angular CLI. The CLI is based on webpack, but it's hiding the complexity and so its difficult to make any significant changes to the underlying configuration.

This is problematic with server-side-rendering. Here the code is executed under node.js and there is no global object (`window`). This PR introduces a simple check against the global object. If we are running outside of a browser a simple dummy-object will help the code to execute until the line `if(!document.getElementsByClassName){return;}` where it will exit silently.

With that change my Angular SSR application executes fine on server-side, too. Inside a browser there should be no difference in the behaviour.

### CODE REVIEW

**Comment by aFarkas** [comment]
I can't take this like it is. Now you have created a globalObject that is leaked in a browser environment.

I think I will come up with a solution myself. Give me some time.

**Comment by JohannesHoppe** [comment]
I actually thought about it for a while and couldn't find a better solution.
I am looking forward to another idea. 😉

Suggestion, we could call it `_globalObject`. I could live with that.

**Comment by aFarkas** [comment]
This is simple just inline your globalObject in the parameter. I also changed it a little bit so you get a dummy object where you can change the config and invoke an empty `init` method as also added the more important plugins.

**Comment by aFarkas** [comment]
You can check https://github.com/aFarkas/lazysizes/tree/node-test branch and report wether this works for you.

**Comment by JohannesHoppe** [comment]
Excellent! I tested your `lazysizes.js` from the `node-test` branch and it works fine! 👍

**Comment by gewentao** [comment]
@JohannesHoppe hi, is there any plan to release node-test branch ?

**Comment by aFarkas** [comment]
Just released 5.1.0

**Pull request closed without merging**
