### PR TITLE
Added override blur-up classes

### PR DESCRIPTION
**Pull request by otmusic**
I added the possibility to change blur-up classes

### CODE REVIEW

**Comment by aFarkas** [comment]
@otmusic 
Thank you for your improvements. I would prefer a PR where the plugin specific code is **not** included in the core script. You can extend the option classes if they are undefined/fals-y.

**Comment by otmusic** [comment]
@aFarkas 
Thanks for your feedback.
I found the `ls-is-cached` class which is adding in core script, and I don't know, how do I change this class without changing in core file?

**Comment by aFarkas** [comment]
> I found the ls-is-cached class which is adding in core script, and I don't know, how do I change this class without changing in core file?
Of course this class can be left inside of the core option. But all other classes should be moved out into the blurUp plugin. Also this class shouldn't be called `blurUpIsCached` maybe `cachedClass` or `fastLoadedClass`.

**Comment by Mendels0n** [comment]
Being able to modify class`ls-is-cached` will be very helpful

**Comment by aFarkas** [comment]
@otmusic 
Is this ready to be re-reviewed?

**Comment by otmusic** [comment]
@aFarkas I was a vacation ) I will check today

**Comment by otmusic** [comment]
@aFarkas
I close this PR and create new because I created a branch with **gh-pages**

**Pull request closed without merging**
