### PR TITLE
Add UMD wrapper for all plugins

### PR DESCRIPTION
**Pull request by claudiobmgrtnr**
Hi

thanks for lazysizes. We are about to use it in a very large project.

**Motiviation**

During the project we realized that the lazysizes plugins won't work properly if lazysizes is not allowed to be stored in `window.lazysizes`.

Unfortunately another script which is out of our project scope is also adding lazysizes to the page and both lazysizes scripts conflict (because of different configs)

We are using a modern build chain which relies on commonJS.
Luckily lazysizes is already using a UMD wrapper which allows us to work with a scoped lazysizes instance. 

The problem is that the plugins don't provide any way to be used with a UMD approach but always rely on a global `window.lazysizes` object.

**Changes**

- All plugins were wrapped with an [UMD factory](https://github.com/umdjs/umd/blob/master/templates/returnExports.js#L17-L37)

**What else?**

All tests pass

### CODE REVIEW

**Comment by aFarkas** [comment]
I will make some little tweaks so that this doesn't result in an API change. (I will still allow a global for some time and I might remove the AMD part.)

**Comment by claudiobmgrtnr** [comment]
Awesome! Please let me know if I can support you in some way.

**Comment by jantimon** [comment]
@aFarkas the UMD factory exports lazySizes as global if (and only if) there is no commonJS or AMDJS module loader

**Comment by aFarkas** [comment]
@jantimon 

Yes, but this is an API change and I don't want this. There is no problem to do it a little bit differently. 

My macbook is broken. I will wait for this. Hope I get it back before this weekend, than I can put something together until Monday.

**Comment by aFarkas** [comment]
@claudiobmgrtnr

Although the JS part is modularized now and you can specify another `trigger` class. One problem remains: Most plugins hook into global DOM events to work. I think, I will add another option to allow changing/adding an "event" prefix. 

Do you have any suggestions about the configuration and implementation for this.

**Comment by jantimon** [comment]
You could also pass the `lazysizes` instance so a module could filter for events using the same lazysize instance

**Pull request merged**
